apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: multi-app-image-updater
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/ssro/argocd-sample.git"
      branch: "main"
      writeBackTarget: "kustomization:./"
  applicationRefs:
    - namePattern: "nginx-staging"
      images:
        - alias: "nginx"
          imageName: "public.ecr.aws/nginx/nginx:1.20"
          commonUpdateSettings:
            forceUpdate: true
            platforms: ["linux/arm64"] # ,linux/amd64"
            updateStrategy: "newest-build"
            allowTags: "regexp:^1\\.29\\.[0-9]+-alpine$"
            ignoreTags: ["latest"]
    - namePattern: "nginx-production"
      images:
        - alias: "nginx"
          imageName: "public.ecr.aws/nginx/nginx:1.20"
          commonUpdateSettings:
            forceUpdate: true
            platforms: ["linux/arm64"] # ,linux/amd64"
            updateStrategy: "newest-build"
            allowTags: "regexp:^1\\.29\\.[0-9]+-alpine$"
            ignoreTags: ["latest"]
