apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-353
  labels:
    app: app-353
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-353
  template:
    metadata:
      labels:
        app: app-353
    spec:
      containers:
      - name: web
        image: httpd
        ports:
        - containerPort: 80
