apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: project-nginx
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  # Allow manifests to deploy from specific GitHub repos
  sourceRepos:
    - "https://github.com/ssro/argocd-sample.git"
  destinations:
    - namespace: "*"
      server: "*"
  # Allow all cluster-scoped resources from being created
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
