apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - cluster: "emca-ip6"
            url: "https://kubernetes.default.svc"
  template:
    metadata:
      name: {{.cluster}}-metrics-server
    spec:
      project: infra
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server
        chart: metrics-server
        targetRevision: "3.12.2"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
