apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx
    project: project-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: nginx
automountServiceAccountToken: false
