apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-838
  labels:
    app: app-838
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-838
  template:
    metadata:
      labels:
        app: app-838
    spec:
      containers:
      - name: web
        image: httpd
        ports:
        - containerPort: 80
