apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          env:
            - name: ENVIRONMENT
              value: "staging"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 30m
              memory: 32Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 5
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    # autoscaling.keda.sh/paused-replicas: "0"
    autoscaling.keda.sh/paused: "false"
  name: nginx
spec:
  minReplicaCount: 0
  maxReplicaCount: 2
  scaleTargetRef:
    name: nginx
  pollingInterval: 15
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      name: nginx
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
          selectPolicy: Max
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "70"
    - type: cron
      metadata:
        timezone: Asia/Singapore
        start: 0 7 * * *
        end: 0 18 * * *
        desiredReplicas: "1" # Setting it up as minReplicaCount
