apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-common-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-httpd
  source:
    repoURL: https://github.com/ssro/argocd-sample.git
    targetRevision: main
    path: ./apps/project-httpd/common/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-httpd-common-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-httpd
  source:
    repoURL: https://github.com/ssro/argocd-sample.git
    targetRevision: main
    path: ./apps/project-httpd/common/production
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
