apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: emca-ip6
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "keda"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: project-infra
      source:
        chart: keda
        repoURL: https://kedacore.github.io/charts
        targetRevision: "2.18.3"
        helm:
          values: |
            image:
              pullPolicy: IfNotPresent
            clusterName: {{ cluster }}
            operator:
              revisionHistoryLimit: 0
            metricsServer:
              revisionHistoryLimit: 0
            logging:
              operator:
                level: error
                format: json
              webhooks:
                level: error
                format: json
            prometheus:
              metricServer:
                enabled: true
                port: 8080
              operator:
                enabled: true
                port: 8080
              webhooks:
                enabled: true
                port: 8080
      destination:
        server: "{{url}}"
        namespace: keda
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - SkipDryRunOnMissingResource=false
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
