apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: devel-ip6
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "keda"
    spec:
      project: project-infra
      source:
        chart: keda
        repoURL: https://kedacore.github.io/charts
        targetRevision: "2.16.1"
        helm:
          values: |
            clusterName: {{ cluster }}
      destination:
        server: "{{url}}"
        namespace: keda
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - SkipDryRunOnMissingResource=false
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
