apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  sourceRepos:
    - "https://github.com/ssro/argocd-sample.git"
    - "https://kedacore.github.io/charts"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
