apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: httpd
    newName: nginx
    newTag: "1.27.0-alpine"
patches:
  - target:
      kind: Deployment
      name: app-603
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 52Mi
          limits:
            cpu: 500m
            memory: 512Mi
