apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: httpd
spec:
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "75"
