apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  project: project-nginx
  source:
    repoURL: https://github.com/ssro/argocd-sample.git
    targetRevision: main
    path: ./apps/project-nginx/nginx/overlays/staging
  destination:
    name: "local"
    # server: https://kubernetes.default.svc
    namespace: nginx-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: nginx-production
   namespace: argocd
   finalizers:
     - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  project: project-nginx
  source:
    repoURL: https://github.com/ssro/argocd-sample.git
    targetRevision: main
    path: ./apps/project-nginx/nginx/overlays/production
  destination:
    name: "local"
    # server: https://kubernetes.default.svc
    namespace: nginx-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
