apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - serviceAccount.yaml
labels:
  - includeSelectors: true
    pairs:
      project: default
