apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: project-httpd
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "https://github.com/ssro/argocd-sample.git"
  destinations:
    - namespace: "*"
      server: "*"
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
